apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-config
  labels:
    app: zookeeper
data:
  ZOOKEEPER_CLIENT_PORT: '2181'
  ZOOKEEPER_TICK_TIME: '2000'
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - nodePort: 32181
      port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    app: zookeeper
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          protocol: TCP
        envFrom:
          - configMapRef:
              name: zk-config
